<?php
$usuario_actual = $_SESSION['valid_user'];


/*LO HE PUESTO A PARTE A PROPOSITO

21 - 04 - 2024 PORQUE ANTES ESTABA EN EL OTRO ARCHIVO
DATOS CONEXION, PERO ESTOY OBLIGADO A PONERLO AQUI
PORQUE ME DIO UN ERROR QUE SE SOLUCIONO PONIENDOLO ASI

EL ERROR ES QUE EN CASO DE QUE ESTA LINEA DE CODIGO ESTÉ EN
EL OTRO FICHERO BASICAMENTE A LA HORA DE INICIAR SESION

APARECERE UN UN ERROR DE VALID USER, BASICAMENTE PORQUE AL INICIARA SESION
TODAVIA NO SE SABE CUAL ES EL VALID USER*/
?>